name: WHIMCPortals
main: me.jackah2.WHIMCPortals.Main
author: Jack Henhapl
version: 2.0
load: POSTWORLD
softdepend: [Multiverse-Core]
commands:
  portal:
    description: Root command for WHIMC Portals
  destination:
    description: Root command for WHIMC Portals