name: ${project.artifactId}
version: ${project.version}
author: Jack Henhapl
api-version: 1.13
main: edu.whimc.portals.Main
description: Create portals for player teleportation
load: POSTWORLD
softdepend: [Multiverse-Core]
commands:
  portal:
    description: Root command for WHIMC Portals
  destination:
    description: Root command for WHIMC Portal